insurance/insurance/Areas/AdminArea/Controllers/Backend_AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static insurance.Areas.AdminArea.Models.AdminArea_Account.Account;
using insurance.Areas.AdminArea.AdminArea_Service;
using static insurance.Models.Custom.FrontAgencyModel;
using insurance.Service;
using insurance.Models;
using insurance.Service.HealthService;
using insurance.HealthApi;
using insurance.Models.Common;
using static insurance.Models.Health.HealthModel;
using insurance.Service.MotorService;
using Post_Utility.Utility;
using insurance.Models.Motor;

namespace insurance.Areas.AdminArea.Controllers
{
    public class Backend_AdministrationController : Controller
    {
        public ActionResult ChangeAdminPassword()
        {
            MemberLogin model = new MemberLogin();
            if (!AdminArea_AccountService.IsBackUserLogin(ref model))
            {
                if (AdminArea_AccountService.LogoutBackendLogin())
                {
                    Response.Redirect("/backend/login");
                }
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult ChangeAdminPassword(MemberLogin model)
        {
            string msg = string.Empty;
            if (!string.IsNullOrEmpty(model.CurrentPassword) && !string.IsNullOrEmpty(model.Password))
            {
                if (AdminArea_AccountService.AdminMemberResetPassword(model, ref msg))
                {
                    TempData["Message"] = msg;
                }
                else
                {
                    ViewBag.Msg = "<div class='col-md-12 text-danger' style='margin-top:10px;'>" + msg + "</div>";
                }
            }
            return View(model);
        }

        public ActionResult Admin_ChangeAgencyPassword()
        {
            CreateAgency model = new CreateAgency();
            return View(model);
        }

        [HttpPost]
        public ActionResult Admin_ChangeAgencyPassword(CreateAgency model)
        {
            string msg = string.Empty;
            if (!string.IsNullOrEmpty(model.Password) && !string.IsNullOrEmpty(model.ConfPassword) && !string.IsNullOrEmpty(model.AgencyID))
            {
                if (AdminArea_AccountService.Admin_ChangeAgencyPassword(model))
                {
                    //TempData["Message"] = "Agency password changed successfully.";
                    TempData["Message"] = "Agency password changed successfully.";
                }
                else
                {
                    ViewBag.Msg = "<div class='col-md-12 text-danger' style='margin-top:10px;'>Some error occured, please try again later!</div>";
                }
            }
            else
            {
                ViewBag.Msg = "<div class='col-md-12 text-danger' style='margin-top:10px;'>Some error occured, please try again later!</div>";
            }
            return View(model);
        }
        public ActionResult AdminEmulateLogin(CreateAgency model)
        {
            if (model.IntAgencyID > 0)
            {
                model = FrontAgencyService.Get_AgencyDetail("", model.IntAgencyID.ToString()).FirstOrDefault();
            }
            return View(model);
        }
        public ActionResult Backend_EmulateLogin(EmulateLogin emodel)
        {
            CreateAgency mode = new CreateAgency();
            try
            {
                if (!string.IsNullOrEmpty(emodel.Remarks.Trim()))
                {
                    MemberLogin lu = new MemberLogin();
                    if (AdminArea_AccountService.IsBackUserLogin(ref lu))
                    {
                        emodel.staffid = lu.LoginId.ToString();
                        emodel.StaffName = lu.FirstName + " " + lu.LastName;
                        emodel.actionType = "insert";

                        emodel = FrontAgencyService.Insert_EmulateloginDetails(emodel);
                        if (!string.IsNullOrEmpty(emodel.EmulateId))
                        {
                            string msg = string.Empty;

                            bool isLogin = AdministrationService.AgencyLogin(emodel.UserId, Security.ApiBase64Decode(emodel.Password), ref msg);
                            if (isLogin)
                            {
                                return Redirect("/agency/dashboard");
                            }
                            else
                            {
                                TempData["Message"] = msg;
                            }
                        }
                    }
                }
                else
                {
                    TempData["Message"] = "login unsuccessful";
                }
            }
            catch (Exception ex)
            {
                ex.ToString();
            }
            return Redirect("/profile/emulate-login");
        }
        public ActionResult AdminEmulatorLogin(EmulateLogin emodel)
        {
            if (emodel.Agencyid > 0)
            {
                CreateAgency model = FrontAgencyService.Get_AgencyDetail("", emodel.Agencyid.ToString()).FirstOrDefault();
                emodel.Agencyid = model.IntAgencyID;
                emodel.AgencyName = model.AgencyName;
                emodel.BusinessPhone = model.BusinessPhone;
                emodel.UserId = model.UserId;
                emodel.BusinessEmailID = model.BusinessEmailID;
                emodel.AgencyAddress = model.Address;
                emodel.Password = model.Password;
            }
            return View(emodel);
        }
        public JsonResult EmulateWithOTP(EmulateLogin emodel)
        {
            List<string> rutStr = new List<string>();
            try
            {
                if (!string.IsNullOrEmpty(emodel.Remarks))
                {
                    MemberLogin lu = new MemberLogin();
                    if (AdminArea_AccountService.IsBackUserLogin(ref lu))
                    {
                        emodel.staffid = lu.LoginId.ToString();
                        emodel.StaffName = lu.FirstName + " " + lu.LastName;
                        emodel.actionType = "insert";
                        emodel.OTP = UtilityClass.GenrateRandomTransactionId(string.Empty, 4, "1234567890");
                        DateTime nowDateTime = DateTime.Now.AddMinutes(5);
                        emodel.OTPExpTime = nowDateTime.ToString("yyyy-MM-dd HH:mm");

                        emodel = FrontAgencyService.Insert_EmulateloginDetails(emodel);
                        if (!string.IsNullOrEmpty(emodel.EmulateId))
                        {
                            string mobmessage = "Your one time password (OTP) is " + emodel.OTP + " for  Agency ID login  : " + emodel.Agencyid + ", valid for next 5 minutes";

                            if (SmsUtility.Send_SeeinsuredSMS(emodel.BusinessPhone, mobmessage))
                            {
                                rutStr.Add("success");
                                rutStr.Add(emodel.EmulateId);
                            }
                            else
                            {
                                rutStr.Add("failed");
                            }
                        }
                    }
                }
                else
                {
                    TempData["Message"] = "login unsuccessful";
                }
            }
            catch (Exception ex)
            {
                ex.ToString();
            }

            return Json(rutStr);
        }
        public JsonResult ResendEmulateLoginWithOTP(EmulateLogin emodel)
        {
            try
            {
                if (!string.IsNullOrEmpty(emodel.EmulateId.Trim()))
                {
                    string newOTP = UtilityClass.GenrateRandomTransactionId(string.Empty, 4, "1234567890");
                    DateTime nowDateTime = DateTime.Now.AddMinutes(15);
                    string newOTPExpTime = nowDateTime.ToString("yyyy-MM-dd HH:mm");
                    emodel.actionType = "update";
                    emodel = FrontAgencyService.Insert_EmulateloginDetails(emodel);
                    if (!string.IsNullOrEmpty(emodel.EmulateId))
                    {
                        string mobmessage = "Your one time password (OTP) is " + emodel.OTP + " for  Agency ID login  : " + emodel.Agencyid + ", valid for next 5 minutes";

                        if (SmsUtility.Send_SeeinsuredSMS(emodel.BusinessPhone, mobmessage))
                        {
                            return Json(true);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                ex.ToString();
            }

            return Json(false);
        }
        public JsonResult EmulateLoginWithOTP(EmulateLogin emodel)
        {
            List<string> retVal = new List<string>();

            try
            {
                if (!string.IsNullOrEmpty(emodel.TempOTP))
                {
                    if (!string.IsNullOrEmpty(emodel.EmulateId.Trim()))
                    {
                        emodel = FrontAgencyService.Get_EmulateDetail(emodel);

                        DateTime expTime = Convert.ToDateTime(emodel.OTPExpTime);
                        if (DateTime.Now < expTime)
                        {
                            if (emodel.TempOTP == emodel.OTP)
                            {
                                string msg = string.Empty;
                                bool isLogin = AdministrationService.AgencyLogin(emodel.UserId, Security.ApiBase64Decode(emodel.Password), ref msg);
                                if (isLogin)
                                {
                                    retVal.Add("success");
                                    retVal.Add("/agency/dashboard");
                                }
                                else
                                {

insurance/insurance/Areas/AdminArea/Views/Backend_Administration/AdminEmulateLogin.cshtml
@model insurance.Models.Custom.FrontAgencyModel.CreateAgency

@{
    ViewBag.Title = "AdminEmulateLogin";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

@section header
{
    <link href="~/Content/css/custom/validationcss.css" rel="stylesheet" />
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
}

<div class="x_panel">
    <div class="x_title">
        <div class="row">
            <div class="col-sm-4">
                <h2><i class="fa fa-lock"></i>&nbsp;Emulate Login (Login Without OTP)</h2>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        @using (Html.BeginForm())
        {
            <div class="row">
                <div class="col-md-5 form-group">
                    <div class="input-group form-validation">
                        <span class="input-group-addon"><span class="fa fa-lock"></span></span>
                        @Html.TextBoxFor(p => p.AgencyName, new { @class = "form-control agencyname form-control ui-autocomplete-input", placeholder = "Enter Agency Name" })
                        @Html.HiddenFor(p => p.IntAgencyID)
                    </div>
                </div>
                <div class="col-md-3 form-group form-validation">
                    <button type="submit" class="btn btn-success" id="searchBtn" onclick="return CheckSearch();">Search</button>
                </div>
            </div>
        }

        @if (Model.IntAgencyID > 0)
        {
            <div class="row box-shad">
                <div class="col-sm-12 form-group" style="margin-top: 15px;">
                    <table class="table table-bordered table-condensed radious">
                        <tbody>
                            <tr>
                                <th class="text-center" style="font-size:15px !important;" colspan="6"><span class="glyphicon glyphicon-user"></span>&nbsp;@Model.AgencyName (@Model.IntAgencyID)</th>
                            </tr>
                            <tr>
                                <th>
                                    Agency Name
                                </th>
                                <td>@Model.AgencyName</td>
                                <th>
                                    Phone
                                </th>
                                <td> @Model.BusinessPhone</td>
                            </tr>
                            <tr>
                                <th>
                                    Login ID
                                </th>
                                <td>@Model.UserId</td>
                                <th>
                                    Email ID
                                </th>
                                <td>@Model.BusinessEmailID</td>
                            </tr>
                            <tr>
                                <th>
                                    Address
                                </th>
                                <td>@Model.Address</td>
                                <th>
                                    Avilable Balance
                                </th>
                                <td>- - -</td>
                            </tr>                            
                        </tbody>
                    </table>
                </div>

                @using (Html.BeginForm("Backend_EmulateLogin", "Backend_Administration", FormMethod.Post, new { target = "_blank" }))
                {
                    <div class="col-sm-12 form-group">
                        @Html.HiddenFor(p => p.UserId)
                        @Html.HiddenFor(p => p.AgencyName)
                        @Html.HiddenFor(p => p.AgencyID)
                        @Html.HiddenFor(p => p.Password)
                        <div class="row">
                            <div class="col-sm-8 ">
                                <div class="input-group form-validation">
                                    <span class="input-group-addon"><span class="fa fa-user"></span></span>
                                    @Html.TextAreaFor(p => p.Remarks, new { @class = "form-control", placeholder = "Enter Remarks.." })
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <input type="submit" class="btn btn-warning emulatelogin" value="Login Agency (@Model.UserId)" onclick="return CheckForm()" />
                                <span class="btn btn-warning temptcss hidden">PLEASE WAIT...<i class="fa fa-spinner fa-spin"></i></span>
                            </div>
                        </div>
                    </div>
                }

            </div>
        }
    </div>
</div>

@section footer
{
    <script>
        $(".agencyname").autocomplete({
            minLength: 3,
            source: function (request, response) {
                $.ajax({
                    url: "/Backend_Administration/AutoComplete_AgencyDetail",
                    type: "POST",
                    dataType: "json",
                    data: { agencyname: request.term },
                    success: function (data) {
                        response($.map(data, function (item) {
                            return { label: item.AgencyName + " (" + item.AgencyID + ")", value: item.AgencyName };
                        }))
                    }
                })
            },
            select: function (event, ui) {
                if (ui.item.value != "") {
                    var agencyid = ui.item.label.split("(");
                    $("#IntAgencyID").val(agencyid[1].replace(")", ""));

                    //$(".maincss").removeClass("hidden");
                }
            },
            response: function (event, ui) {
                if (!ui.content.length) {
                    var noResult = { value: "", label: "No Agency Name matching" };
                    ui.content.push(noResult);
                }
            },
            messages: {
                noResults: "", results: ""
            }
        });
    </script>
    <script src="~/Content/js/custom/common.js"></script>
    <script>
        CheckSearch = () => { if (CheckFocusBlankValidation("AgencyName")) return !1; }
        function CheckForm() {
            if (CheckFocusBlankValidation("Remarks")) return !1; $(".temptcss").removeClass("hidden"); $(".emulatelogin").addClass("hidden");
            setTimeout(function () { $("#Remarks").val(""); $(".temptcss").addClass("hidden"); $(".emulatelogin").removeClass("hidden"); }, 5000);
        }
    </script>
}

insurance/insurance/Areas/AdminArea/Views/Backend_Administration/AdminExtranetBooking.cshtml
@model insurance.Models.Custom.FrontAgencyModel.CreateAgency

@{
    ViewBag.Title = "AdminExtranetBooking";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

@section header
{
    <link href="~/Content/css/custom/validationcss.css" rel="stylesheet" />
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
}

<div class="x_panel">
    <div class="x_title">
        <div class="row">
            <div class="col-sm-4">
                <h2><i class="fa fa-lock"></i>&nbsp;Search Agency</h2>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        @using (Html.BeginForm())
        {
            <div class="row">
                <div class="col-md-5 form-group">
                    <div class="input-group form-validation">
                        <span class="input-group-addon"><span class="fa fa-lock"></span></span>
                        @Html.TextBoxFor(p => p.AgencyName, new { @class = "form-control agencyname form-control ui-autocomplete-input", placeholder = "Enter Agency Name" })
                        @Html.HiddenFor(p => p.IntAgencyID)
                    </div>
                </div>
                <div class="col-md-3 form-group form-validation">
                    <button type="submit" class="btn btn-success" id="searchBtn" onclick="return CheckSearch();">Search</button>
                </div>
            </div>
        }

        @if (Model.IntAgencyID > 0)
        {
            <div class="row box-shad">
                <div class="col-sm-12 form-group" style="margin-top: 15px;">
                    <table class="table table-bordered table-condensed radious">
                        <tbody>
                            <tr>
                                <th class="text-center" style="font-size:15px !important;" colspan="6"><span class="glyphicon glyphicon-user"></span>&nbsp;@Model.AgencyName (@Model.IntAgencyID)</th>
                            </tr>
                            <tr>
                                <th>
                                    Agency Name
                                </th>
                                <td>@Model.AgencyName</td>
                                <th>
                                    Phone
                                </th>
                                <td> @Model.BusinessPhone</td>
                            </tr>
                            <tr>
                                <th>
                                    Login ID
                                </th>
                                <td>@Model.UserId</td>
                                <th>
                                    Email ID
                                </th>
                                <td>@Model.BusinessEmailID</td>
                            </tr>
                            <tr>
                                <th>
                                    Address
                                </th>
                                <td>@Model.Address</td>
                                <th>
                                    Available Balance
                                </th>
                                <td>- - -</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="col-sm-12">
                    <div class="col-sm-offset-8 ">
                        <input type="submit" class="btn btn-warning pull-right" value="Create Proposal" onclick="return CheckForm('@Model.IntAgencyID')" />
                    </div>

                </div>


            </div>
        }
    </div>
</div>

@section footer
{
    <script>
        $(".agencyname").autocomplete({
            minLength: 3,
            source: function (request, response) {
                $.ajax({
                    url: "/Backend_Administration/AutoComplete_AgencyDetail",
                    type: "POST",
                    dataType: "json",
                    data: { agencyname: request.term },
                    success: function (data) {
                        response($.map(data, function (item) {
                            return { label: item.AgencyName + " (" + item.AgencyID + ")", value: item.AgencyName };
                        }))
                    }
                })
            },
            select: function (event, ui) {
                if (ui.item.value != "") {
                    var agencyid = ui.item.label.split("(");
                    $("#IntAgencyID").val(agencyid[1].replace(")", ""));

                    //$(".maincss").removeClass("hidden");
                }
            },
            response: function (event, ui) {
                if (!ui.content.length) {
                    var noResult = { value: "", label: "No Agency Name matching" };
                    ui.content.push(noResult);
                }
            },
            messages: {
                noResults: "", results: ""
            }
        });
    </script>
    <script src="~/Content/js/custom/common.js"></script>
    <script>
        CheckSearch = () => { if (CheckFocusBlankValidation("AgencyName")) return !1; }
        function CheckForm(agencyId) {
            window.location.href = "/profile/health/extranet-create-proposal?agencyId=" + agencyId;
        }
    </script>
}

insurance/insurance/Areas/AdminArea/Views/Backend_Administration/AdminExtranetBooking_Motor.cshtml
@model insurance.Models.Custom.FrontAgencyModel.CreateAgency
@{
    ViewBag.Title = "AdminExtranetBooking_Motor";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

@section header
{
    <link href="~/Content/css/custom/validationcss.css" rel="stylesheet" />
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
}

<div class="x_panel">
    <div class="x_title">
        <div class="row">
            <div class="col-sm-4">
                <h2><i class="fa fa-lock"></i>&nbsp;Search Agency</h2>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        @using (Html.BeginForm())
        {
            <div class="row">
                <div class="col-md-5 form-group">
                    <div class="input-group form-validation">
                        <span class="input-group-addon"><span class="fa fa-lock"></span></span>
                        @Html.TextBoxFor(p => p.AgencyName, new { @class = "form-control agencyname form-control ui-autocomplete-input", placeholder = "Enter Agency Name" })
                        @Html.HiddenFor(p => p.IntAgencyID)
                    </div>
                </div>
                <div class="col-md-3 form-group form-validation">
                    <button type="submit" class="btn btn-success" id="searchBtn" onclick="return CheckSearch();">Search</button>
                </div>
            </div>
        }

        @if (Model.IntAgencyID > 0)
        {
            <div class="row box-shad">
                <div class="col-sm-12 form-group" style="margin-top: 15px;">
                    <table class="table table-bordered table-condensed radious">
                        <tbody>
                            <tr>
                                <th class="text-center" style="font-size:15px !important;" colspan="6"><span class="glyphicon glyphicon-user"></span>&nbsp;@Model.AgencyName (@Model.IntAgencyID)</th>
                            </tr>
                            <tr>
                                <th>
                                    Agency Name
                                </th>
                                <td>@Model.AgencyName</td>
                                <th>
                                    Phone
                                </th>
                                <td> @Model.BusinessPhone</td>
                            </tr>
                            <tr>
                                <th>
                                    Login ID
                                </th>
                                <td>@Model.UserId</td>
                                <th>
                                    Email ID
                                </th>
                                <td>@Model.BusinessEmailID</td>
                            </tr>
                            <tr>
                                <th>
                                    Address
                                </th>
                                <td>@Model.Address</td>
                                <th>
                                    Available Balance
                                </th>
                                <td>- - -</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="col-sm-12">
                    <div class="col-sm-offset-8 ">
                        <input type="submit" class="btn btn-warning pull-right" value="Create Proposal" onclick="return CheckForm('@Model.IntAgencyID')" />
                    </div>

                </div>


            </div>
        }
    </div>
</div>

@section footer
{
    <script>
        $(".agencyname").autocomplete({
            minLength: 3,
            source: function (request, response) {
                $.ajax({
                    url: "/Backend_Administration/AutoComplete_AgencyDetail",
                    type: "POST",
                    dataType: "json",
                    data: { agencyname: request.term },
                    success: function (data) {
                        response($.map(data, function (item) {
                            return { label: item.AgencyName + " (" + item.AgencyID + ")", value: item.AgencyName };
                        }))
                    }
                })
            },
            select: function (event, ui) {
                if (ui.item.value != "") {
                    var agencyid = ui.item.label.split("(");
                    $("#IntAgencyID").val(agencyid[1].replace(")", ""));

                    //$(".maincss").removeClass("hidden");
                }
            },
            response: function (event, ui) {
                if (!ui.content.length) {
                    var noResult = { value: "", label: "No Agency Name matching" };
                    ui.content.push(noResult);
                }
            },
            messages: {
                noResults: "", results: ""
            }
        });
    </script>
    <script src="~/Content/js/custom/common.js"></script>
    <script>
        CheckSearch = () => { if (CheckFocusBlankValidation("AgencyName")) return !1; }
        function CheckForm(agencyId) {
            window.location.href = "/profile/motor/extranet-create-proposal?agencyId=" + agencyId;
        }
    </script>
}